name: setup-gke-gcloud-auth-plugin
description: Installs gke-gcloud-auth-plugin
branding:
  icon: lock
  color: green

runs:
  using: composite
  steps:
    - name: Install gke-gcloud-auth-plugin
      shell: bash
      run: |
        REPO_URL="https://packages.cloud.google.com/apt"
        echo "deb [signed-by=/etc/apt/trusted.gpg.d/cloud.google.gpg] $REPO_URL cloud-sdk main" | sudo tee -a /etc/apt/sources.list.d/google-cloud-sdk.list >/dev/null
        curl -fsSLo - https://packages.cloud.google.com/apt/doc/apt-key.gpg | sudo gpg --dearmor -o /etc/apt/trusted.gpg.d/cloud.google.gpg

        sudo apt update -y
        sudo apt install -y google-cloud-cli-gke-gcloud-auth-plugin
        sudo apt install -y google-cloud-sdk-gke-gcloud-auth-plugin 
